### ISSUE TITLE
填了repo的url后显示request failed

### ISSUE THREAD

**Issue by LewisNepenthes** [gissue/gissue.github.io#6]
请问现在还能用吗？填了repo的url后显示request failed。

![image](https://user-images.githubusercontent.com/59465440/95804076-532f4780-0d34-11eb-9d32-cbed5c9a19cf.png)

**Comment by kytrun** [comment]
应该是能用的，确保仓库存在并且是公开的

**Comment by LewisNepenthes** [comment]
- 似乎还是不行，我截图上的仓库是private的，然后我将其转换为public。request failed。
- 然后我在另一个原本就是public的仓库提issue，点download后也是failed。是我的链接填写有误吗？
> https://github.com/LewisNepenthes/Fantastic-Doodle
- 又或者和网络有关系？

**Comment by kytrun** [comment]
![image](https://user-images.githubusercontent.com/32519285/95813308-28e88480-0d4a-11eb-9a8d-c7cd5805b9dd.png)

**Comment by LewisNepenthes** [comment]
- Totally confused... 我现在去download又可以了，包括之前从private改到public的库。非常感谢！
- 另外想问一下download下来的issue只有一开始写issue时的comment，下面追加的comment都没有，比如我现在写的这条，这是正常的吗？

**Comment by kytrun** [comment]
目前是这样的，只能导出 issue 创建时的内容

**Comment by LewisNepenthes** [comment]
了解。非常感谢！
